#ifndef MY_HTTP_H
#define MY_HTTP_H

#define MAX_RECV_BUF 2048
#define MAX_STATUS_LEN 64
#define HTTP_MAX_HEADERS 100
#define HTTP_STATUS_COUNT 3
#define HTTP_REASON_MAX_LEN 64
#define HTTP_METHOD_MAX_LEN 16
#define HTTP_PATH_MAX_LEN 256
#define HTTP_VERSION_MAX_LEN 16
#define HTTP_HEADER_NAME_MAX_LEN 64
#define HTTP_HEADER_VALUE_MAX_LEN 256
#define HTTP_MAX_RESPONSE_SIZE 8192

#endif // MY_HTTP_H